name = "next-on-pages-test"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "test-d1"
database_id = "f9138582-09d1-4172-a2af-273853cba524"
preview_id = "DB"


[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "test-d1-preview"
database_id = "51d69209-8e7b-44e1-9686-6cb5126e1097"
